### ISSUE TITLE
Unable to update no_middle_name attribute

### ISSUE THREAD

**Issue by hillmandj** [checkr/checkr-ruby#15]
Just noticed you actually had a PR with the same code open, but this has become necessary for us to backfill old candidates with the appropriate no_middle_name attribute: https://github.com/checkr/checkr-ruby/pull/14

Please keep me posted about whether or not you can merge this. Many thanks.

**Comment by jperichon** [comment]
Fix in https://github.com/checkr/checkr-ruby/pull/8, thanks!
