### ISSUE TITLE
Naming conflict can cause breakage.

### ISSUE THREAD

**Issue by jclay** [checkr/checkr-ruby#4]
TL;DR The way that `checkr-ruby` resolves constant names means they can conflict with constants in your own app.

This was a difficult one to debug. Here's where it started.

Rails Console:
```
pry(main)> Checkr::Candidate.all
NoMethodError: undefined method `construct' for Report:Class
/Users/[...]/bundler/gems/checkr-ruby-aaa9a0399e3c/lib/checkr/api_list.rb:63:in `block (2 levels) in refresh_from_hash'
```

I eventually track down some logic in the `APIList.costructor` method:
```ruby
    def self.constructor(klass)
      lambda do |json|
        klass = Util.constantize(klass) unless klass.is_a?(Class)

        instance = self.new
        instance.api_list_klass = klass
        instance.refresh_from(json)
      end
    end
```

Let's see what's going on with `Util.constantize`
```
pry(main)> Checkr::Util.constantize("Geo")
=> Checkr::Geo // Looks good!


pry(main)> Checkr::Util.constantize("ReportList")
=> Checkr::ReportList // Likewise

pry(main)> Checkr::Util.constantize("Report")
=> Report //Uh-oh this looks like a model I'm using.

pry(main)> Checkr::Util.constantize("Report").some_model_method?
=> true // Yep - that's my model class.
```

Taking a look at the culprit...
```ruby
# lib/checkr/util.rb
def self.constantize(str, prefix=false)
      str = str.to_s
      begin
        str.split('::').reduce(Module, :const_get) # Right here
      rescue NameError => e
        if prefix
          raise e
        else
          p = "#{self.name}".split("::").first
          constantize("#{p}::#{str}", true)
        end
      end
    end
```

This should be fixed to handle searching within the Checkr module only. Otherwise, If you use any of the Checkr constant names in your project, you will experience breakage.

**Comment by joncalhoun** [comment]
:+1:  I think this was fixed in another lib I worked on and I forgot to port changed here. Let me go look fast.

**Comment by joncalhoun** [comment]
Fixed in https://github.com/checkr/checkr-ruby/commit/078963d97e2113ababbc00bca4ce0b077f306857 and pushed to rubygems as 1.0.2.

Enjoy!
