### ISSUE TITLE
Cannot determine live/test mode from API key?

### ISSUE THREAD

**Issue by lserman** [checkr/checkr-ruby#7]
Sorry if I missed it, but I don't think there is a way to test if you are using the live or test version of the API, given the API key. It would be nice to have `Checkr.test_mode?` or something like that. In my case, I want to link to reports from the administrative side of the website, but I have no way of knowing whether or not I need to append "?test=true" to the URL or not. Since I'm using test mode on "production" for the time being, I can't rely on `Rails.env` either.

**Comment by cjford** [comment]
Unfortunately the Checkr API doesn't currently support responding with information about test/live environment settings. I suggest saving which mode a key is associated with on the client side as it should be available to you when the key is generated.
