### ISSUE TITLE
Connect to Staging environment?

### ISSUE THREAD

**Issue by tupakapoor** [checkr/checkr-ruby#74]
How can this SDK be used to connect to the staging environment found at https://dashboard.checkrhq-staging.net?

**Comment by jrae** [comment]
Looking into this too today.. Seems we need to point to here

`Note: The staging account uses the API host URL: https://api.checkr-staging.com/v1 for all calls.`

https://docs.checkr.com/#section/Staging-Accounts/Configure-your-staging-account

But the base url is hardcoded in the GEM

```
module Checkr
  @api_base = "https://api.checkr.com"
```

Would be nice to be able to override with a 

ENV.fetch('CHECKR_API_BASE', "https://api.checkr.com")

Considering forking to test these new API updates

**Comment by tupakapoor** [comment]
> I think you should be able to just set it with something like this in your initializer code
> 
> Checkr.api_base = "https://api.checkr-stagi

This is correct, I realized this last night 😳 Thanks for responding!
